# cgroup.conf for ultron cluster
CgroupMountpoint="/sys/fs/cgroup"
CgroupAutomount=yes

# Prevent jobs from taking more RAM than requested
ConstrainRAMSpace=yes
# If a job exceeds RAM, Slurm will kill it (prevents system freeze)
AllowedRAMSpace=100
# Don't let students swap to disk (keeps performance high)
ConstrainSwapSpace=yes

# Lock jobs to specific CPU cores
ConstrainCores=yes

# GPU Isolation (Critical for your 4090s)
ConstrainDevices=yes
